# Generated by Django 2.1.5 on 2019-01-20 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=20)),
                ('video_desc', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2019, 1, 20, 3, 13, 53, 242017, tzinfo=utc))),
            ],
        ),
    ]
