# Generated by Django 2.1.5 on 2019-01-21 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 1, 53, 26, 730068, tzinfo=utc)),
        ),
    ]
