# Generated by Django 2.1.5 on 2019-01-21 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video_request', '0002_auto_20190120_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 1, 56, 26, 48704, tzinfo=utc)),
        ),
    ]
